name: Rodar Scraper de Resultados

on:
  schedule:
    # Executa a cada 10 minutos
    - cron: '*/10 * * * *'
  workflow_dispatch:
    # Permite executar manualmente a partir do separador "Actions"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v3

      - name: 2. Configurar o Node.js
        uses: actions/setup-node@v3
        with:
          # CORREÇÃO: Usar a versão 20 do Node.js para melhor compatibilidade
          node-version: '20'

      - name: 3. Instalar as dependências
        run: npm install

      - name: 4. Executar o Scraper
        run: node server.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
