name: Rodar Scraper de Resultados

on:
  schedule:
    # Executa a cada 10 minutos
    - cron: '*/10 * * * *'
  workflow_dispatch:
    # Permite executar manualmente a partir do separador "Actions"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v4

      - name: 2. Configurar o Navegador (Chrome) para o Puppeteer
        # Esta ação instala o Google Chrome e outras dependências necessárias
        # para o Puppeteer funcionar corretamente no ambiente do GitHub.
        uses: browser-actions/setup-chrome@v1

      - name: 3. Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 4. Instalar as dependências
        run: npm install

      - name: 5. Executar o Scraper
        run: node server.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
